version: '3.8'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '5050:80'
