version: '3.8'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '5050:80'

volumes:
  db_data:
  pgadmin_data:
